[package]
name = "lord-drawquaad"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
license = "MIT / Apache-2.0"

[dependencies]
gl = "0.6"

[dev-dependencies]
image = "0.12"

[dev-dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

